version: "3"
services:
  apache:
    volumes:
      - ./elmsln:/var/www/elmsln
    build:
      context: .
      dockerfile: DockerfileApache
    links:
      - db
    ports:
      - "80:80"

  db:
    build:
      context: .
      dockerfile: DockerfileMySQL
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
